version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: main
    volumes:
      - ../mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ../mongodb/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  crawler1:
    image: crawler
    restart: always
    container_name: crawler1
    depends_on: 
      - mongo

  crawler2:
    image: crawler
    restart: always
    container_name: crawler2
    depends_on: 
      - mongo

  haproxy:
    image: haproxy:2.3-alpine
    restart: always
    container_name: haproxy
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ../haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on: 
      - crawler1
      - crawler2

  mock-server:
    image: halverneus/static-file-server
    restart: always
    container_name: mock-server
    environment: 
      DEBUG: 'true'
      SHOW_LISTING: 'true'
      PORT: 8080
      FOLDER: /test-data
    volumes:
      - ../test-data:/test-data